import React, { Component } from 'react';
import { Container } from 'react-bootstrap';

export default class About extends Component {

    render() {
        return (
            <Container style={{ paddingTop: 80 }}>
                <h2>About</h2>
                <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed lacinia pulvinar feugiat. Donec purus nisl, blandit nec ipsum sed, eleifend molestie ligula. Interdum et malesuada fames ac ante ipsum primis in faucibus. Integer dui odio, dictum quis vehicula et, vestibulum ut ante. Nam eu euismod erat. Quisque in semper felis, rutrum mollis sapien. Sed dignissim vel est vitae luctus. Quisque felis libero, malesuada ac tempus commodo, condimentum eget lectus. Ut enim dolor, porttitor eleifend velit vitae, viverra interdum justo. Fusce at nunc vel ex tempor finibus sed in lacus. Nullam iaculis sem ut elit mattis tincidunt et at nulla. Donec at ex vitae orci tincidunt volutpat at id velit. Cras lobortis sapien in rutrum efficitur. Nulla condimentum hendrerit risus, at laoreet elit ullamcorper vitae. Sed pretium venenatis dolor, quis ullamcorper turpis lacinia consectetur.</p>
                <p>Sed finibus tristique lectus, ac pulvinar mi consectetur viverra. Aenean vitae venenatis metus. Fusce dignissim mattis sagittis. Nulla urna sapien, varius sit amet nisi at, interdum venenatis leo. Morbi libero dolor, lobortis sit amet tincidunt in, pulvinar a libero. In efficitur lacinia ligula, et eleifend mi blandit et. Phasellus vel nisi posuere, tincidunt erat ac, ultrices ipsum. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Nulla eget eros at ex tempor interdum eget sagittis tortor. Suspendisse volutpat augue ac velit maximus finibus. Ut ullamcorper, enim nec suscipit interdum, elit sapien facilisis lectus, a laoreet lorem tellus vel neque. Morbi tellus risus, accumsan nec sodales et, rhoncus vel neque. Curabitur dapibus felis facilisis nisl suscipit, sit amet cursus magna lacinia. Aenean gravida massa sapien, eu ornare dolor imperdiet ut. Phasellus id leo auctor, euismod augue eu, pharetra dolor.</p>
                <p>Praesent ut turpis ut tellus feugiat iaculis sed eget dolor. Ut cursus massa condimentum magna maximus posuere. Nulla rhoncus nisl ac erat dapibus, vel imperdiet libero maximus. Morbi massa odio, commodo vel porttitor eu, gravida sit amet quam. Phasellus elit elit, bibendum sit amet libero eget, lacinia mattis dui. Praesent luctus euismod libero, a rutrum eros tempus in. Sed commodo tristique odio, eget eleifend nunc fringilla vitae. Nam nulla nulla, porttitor in porta sed, consequat in elit. Nullam hendrerit ultrices nisi, vitae maximus justo.</p>
                <p>Suspendisse sed rhoncus mi. Pellentesque dictum, felis gravida eleifend malesuada, eros quam venenatis justo, ut euismod lacus tortor sit amet ligula. In hac habitasse platea dictumst. Vivamus ultricies enim eget leo commodo, in ornare ligula mattis. Proin imperdiet velit eu enim fringilla placerat. Nulla cursus dictum lacus, et venenatis magna dapibus a. Aliquam erat volutpat. Mauris ut rutrum lorem, in dapibus sapien. Phasellus eget convallis sapien, nec vulputate magna. Curabitur laoreet libero at ultrices bibendum. Pellentesque purus libero, vulputate ac semper nec, ultricies nec massa. Aliquam tempor, orci aliquam molestie cursus, orci nunc efficitur metus, vel dictum urna enim in lorem. Donec congue lectus eget nunc consectetur aliquam.</p>
                <p>Duis sed hendrerit mi. Pellentesque tempus dictum arcu id placerat. Morbi semper accumsan ante, vitae dictum lacus congue quis. Fusce condimentum suscipit posuere. Vestibulum non sem dui. Quisque luctus ut quam nec eleifend. Suspendisse fermentum augue et condimentum malesuada. Phasellus porttitor ex purus, ut aliquam nulla tincidunt vel. Vestibulum a arcu et magna accumsan varius nec a dolor. Suspendisse potenti. Curabitur ligula orci, placerat quis ipsum in, ultrices interdum mauris.</p>
            </Container>
        )
    }
}